title: Stackbit Vanilla Theme
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: A vanilla theme for Stackbit
header:
  title: Russell Callahan
  has_nav: true
  nav_links:
    - label: Home
      url: /
    - label: Publications
      url: /generic/
    - label: CV
      url: /elements/
footer:
  content: >-
    &copy; Stackbit. All rights reserved. This Jamstack site was created on <a
    href="https://www.stackbit.com" target="_blank" rel="noopener">Stackbit</a>.
    Get yours <a href="https://app.stackbit.com/create?theme=vanilla"
    target="_blank" rel="noopener">here</a>.
  has_social: true
  social_links:
    - label: Twitter
      url: 'https://twitter.com/rp_callahan'
      new_window: true
    - label: Google Scholar
      url: 'https://scholar.google.com/citations?user=k76PA1kAAAAJ&hl=en'
      new_window: true
    - label: ORCiD
      url: 'https://dev.to/'
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
